services:
  app-test:
    build:
      context: ../..
      dockerfile: infra/api/Dockerfile.test
    container_name: app-test
    env_file:
      - ../../.env.test
    environment:
      - TEST_DATABASE_HOST=postgres
      - TEST_DATABASE_PORT=${TEST_DATABASE_PORT}
      - TEST_DATABASE_USER=${TEST_DATABASE_USER}
      - TEST_DATABASE_PASSWORD=${TEST_DATABASE_PASSWORD}
      - TEST_DATABASE_NAME=${TEST_DATABASE_NAME}
      - GOTRUE_URL=http://gotrue:9999
      - GOTRUE_SERVICE_KEY=${GOTRUE_SERVICE_KEY}
    volumes:
      - ../..:/rabi-food-core
    working_dir: /rabi-food-core
    networks:
      - test
    command: task test-local

networks:
  test:
    name: test
    external: true
