name: Deploy Production

on:
  release:
    types: [published]

jobs:
  test:
    uses: ./.github/workflows/test.yml

  deploy:
    needs: [test]
    runs-on: ubuntu-24.04
    container: golang:1.26.1

    defaults:
      run:
        working-directory: app

    steps:
      - name: Fetch Repository
        uses: actions/checkout@v5

      - name: Generate binary
        run: go build -o rabi-food-core main.go

      - name: Rename binary
        run: mv rabi-food-core rabi-food-core@latest

      - name: Run Migrations
        env:
          DATABASE_HOST: ${{ secrets.DATABASE_HOST_PRODUCTION }}
          DATABASE_USER: ${{ secrets.DATABASE_USER_PRODUCTION }}
          DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD_PRODUCTION }}
          DATABASE_PORT: ${{ secrets.DATABASE_PORT_PRODUCTION }}
          DATABASE_NAME: ${{ secrets.DATABASE_NAME_PRODUCTION }}
        run: |
          go run github.com/pressly/goose/v3/cmd/goose@v3.27.0 \
            -dir libs/database/migrations postgres \
            "host=${DATABASE_HOST} user=${DATABASE_USER} password=${DATABASE_PASSWORD} port=${DATABASE_PORT} dbname=${DATABASE_NAME}" \
            up

      - name: Copy binary
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST_PRODUCTION }}
          username: ${{ secrets.SSH_USER_PRODUCTION }}
          key: ${{ secrets.SSH_KEY_PRODUCTION }}
          source: "./app/rabi-food-core@latest"
          target: "~/"

      - name: Deploy script
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST_PRODUCTION }}
          username: ${{ secrets.SSH_USER_PRODUCTION }}
          key: ${{ secrets.SSH_KEY_PRODUCTION }}
          script: |
            mv rabi-food-core@latest rabi-food-core
            chmod 700 rabi-food-core
            sudo systemctl restart rabi-food-core.service
