-- +goose Up
CREATE SCHEMA IF NOT EXISTS SUBSCRIPTION;

CREATE TABLE
    SUBSCRIPTION.subscriptions (
        id UUID PRIMARY KEY,
        root_subscription_id UUID REFERENCES SUBSCRIPTION.subscriptions (id),
        subscription_group_id UUID,
        tenant_id UUID NOT NULL REFERENCES iam.tenants (id),
        user_id UUID NOT NULL REFERENCES auth.users (id),
        product_id UUID NOT NULL REFERENCES CATALOG.products (id),
        quantity SMALLINT NOT NULL,
        unit_price BIGINT NOT NULL,
        delivery_days JSONB,
        delivery_weekdays_mask SMALLINT NOT NULL DEFAULT 0,
        notes TEXT,
        total_cycles BIGINT NOT NULL,
        remaining_cycles BIGINT NOT NULL,
        cycle_discount BIGINT NOT NULL DEFAULT 0,
        cutoff_offset_minutes INTEGER NOT NULL DEFAULT 0,
        auto_renew BOOLEAN NOT NULL DEFAULT TRUE,
        max_attempts_per_order SMALLINT NOT NULL DEFAULT 1,
        items_total BIGINT NOT NULL DEFAULT 0,
        items_discount BIGINT NOT NULL DEFAULT 0,
        payment_amount BIGINT NOT NULL,
        payment_status VARCHAR(20) NOT NULL,
        external_payment_id VARCHAR(100) NOT NULL,
        status VARCHAR(20),
        created_at TIMESTAMPTZ,
        updated_at TIMESTAMPTZ,
        CONSTRAINT uq_subscriptions_external_payment_id UNIQUE (external_payment_id)
    );

COMMENT ON COLUMN SUBSCRIPTION.subscriptions.root_subscription_id IS 'Reference to the original subscription this was renewed from. NULL for subscriptions created directly.';

COMMENT ON COLUMN SUBSCRIPTION.subscriptions.subscription_group_id IS 'Groups subscriptions created together in the same purchase. Generated by the application at checkout time.';

COMMENT ON COLUMN SUBSCRIPTION.subscriptions.product_id IS 'The subscribed product. One subscription row per product.';

COMMENT ON COLUMN SUBSCRIPTION.subscriptions.quantity IS 'Quantity of the product per cycle.';

COMMENT ON COLUMN SUBSCRIPTION.subscriptions.unit_price IS 'Unit price of the product in cents at the time of subscription.';

COMMENT ON COLUMN SUBSCRIPTION.subscriptions.delivery_weekdays_mask IS 'Bitmask of weekdays for recurring delivery. Bit 0 = Sunday, bit 1 = Monday, ..., bit 6 = Saturday.';

COMMENT ON COLUMN SUBSCRIPTION.subscriptions.delivery_days IS 'JSON array of specific delivery dates, used when scheduling is not based on a weekly mask.';

COMMENT ON COLUMN SUBSCRIPTION.subscriptions.total_cycles IS 'Total number of cycles contracted in the subscription.';

COMMENT ON COLUMN SUBSCRIPTION.subscriptions.remaining_cycles IS 'Cycles yet to be executed. Decremented on each generated order.';

COMMENT ON COLUMN SUBSCRIPTION.subscriptions.cycle_discount IS 'Fixed discount per cycle in cents.';

COMMENT ON COLUMN SUBSCRIPTION.subscriptions.cutoff_offset_minutes IS 'Minutes before the delivery window start at which the cycle order is automatically generated.';

COMMENT ON COLUMN SUBSCRIPTION.subscriptions.auto_renew IS 'When true, automatically creates a new subscription once remaining cycles reach zero.';

COMMENT ON COLUMN SUBSCRIPTION.subscriptions.max_attempts_per_order IS 'Maximum number of delivery attempts per generated order for this subscription.';

COMMENT ON COLUMN SUBSCRIPTION.subscriptions.items_total IS 'Gross sum of items in cents, before discounts.';

COMMENT ON COLUMN SUBSCRIPTION.subscriptions.items_discount IS 'Total discount applied to items in cents.';

COMMENT ON COLUMN SUBSCRIPTION.subscriptions.payment_amount IS 'Amount charged per cycle in cents.';

COMMENT ON COLUMN SUBSCRIPTION.subscriptions.payment_status IS 'Financial lifecycle.';

COMMENT ON COLUMN SUBSCRIPTION.subscriptions.external_payment_id IS 'Recurring contract ID from the external payment gateway.';

COMMENT ON COLUMN SUBSCRIPTION.subscriptions.status IS 'Subscription lifecycle.';

CREATE INDEX idx_subscriptions_root_subscription_id ON SUBSCRIPTION.subscriptions (root_subscription_id);

CREATE INDEX idx_subscriptions_subscription_group_id ON SUBSCRIPTION.subscriptions (subscription_group_id);

CREATE INDEX idx_subscriptions_tenant_id ON SUBSCRIPTION.subscriptions (tenant_id);

CREATE INDEX idx_subscriptions_user_id ON SUBSCRIPTION.subscriptions (user_id);

CREATE INDEX idx_subscriptions_product_id ON SUBSCRIPTION.subscriptions (product_id);

CREATE INDEX idx_subscriptions_delivery_weekdays_mask ON SUBSCRIPTION.subscriptions (delivery_weekdays_mask);

CREATE INDEX idx_subscriptions_remaining_cycles ON SUBSCRIPTION.subscriptions (remaining_cycles);

CREATE INDEX idx_subscriptions_payment_status ON SUBSCRIPTION.subscriptions (payment_status);

CREATE INDEX idx_subscriptions_status ON SUBSCRIPTION.subscriptions (status);

CREATE TABLE
    SUBSCRIPTION.subscription_configs (
        tenant_id UUID PRIMARY KEY NOT NULL REFERENCES iam.tenants (id),
        is_open BOOLEAN NOT NULL,
        max_attempts_per_order SMALLINT,
        discount_rules JSONB,
        cutoff_offset_minutes INTEGER,
        order_lead_minutes SMALLINT,
        updated_at TIMESTAMPTZ
    );

COMMENT ON COLUMN SUBSCRIPTION.subscription_configs.is_open IS 'Whether the tenant is accepting new subscriptions.';

COMMENT ON COLUMN SUBSCRIPTION.subscription_configs.max_attempts_per_order IS 'Tenant-level override for max delivery attempts per order. Takes precedence over the individual subscription value when set.';

COMMENT ON COLUMN SUBSCRIPTION.subscription_configs.discount_rules IS 'JSON array of progressive discount rules based on contracted cycle volume.';

COMMENT ON COLUMN SUBSCRIPTION.subscription_configs.cutoff_offset_minutes IS 'Tenant-level override for the cutoff offset in minutes. Takes precedence over the individual subscription value when set.';

COMMENT ON COLUMN SUBSCRIPTION.subscription_configs.order_lead_minutes IS 'Minimum hours required between order placement and delivery start time. Orders placed with less than this lead time are scheduled for the following week.';

CREATE TABLE
    SUBSCRIPTION.subscription_deliveries (
        id UUID PRIMARY KEY,
        subscription_id UUID NOT NULL REFERENCES SUBSCRIPTION.subscriptions (id),
        scheduled_date TIMESTAMPTZ,
        start_hour SMALLINT NOT NULL,
        end_hour SMALLINT NOT NULL,
        cutoff_at TIMESTAMPTZ NOT NULL,
        status VARCHAR(20),
        delivery_attempts SMALLINT,
        max_delivery_attempts SMALLINT,
        created_at TIMESTAMPTZ,
        updated_at TIMESTAMPTZ,
        CONSTRAINT subscription_delivery_unique UNIQUE (subscription_id, scheduled_date)
    );

COMMENT ON COLUMN SUBSCRIPTION.subscription_deliveries.scheduled_date IS 'Scheduled date for this delivery.';

COMMENT ON COLUMN SUBSCRIPTION.subscription_deliveries.start_hour IS 'Start of the delivery window (0-23).';

COMMENT ON COLUMN SUBSCRIPTION.subscription_deliveries.end_hour IS 'End of the delivery window (0-23).';

COMMENT ON COLUMN SUBSCRIPTION.subscription_deliveries.cutoff_at IS 'Deadline for modifications to this delivery order. The order is locked after this timestamp.';

COMMENT ON COLUMN SUBSCRIPTION.subscription_deliveries.status IS 'Delivery status.';

COMMENT ON COLUMN SUBSCRIPTION.subscription_deliveries.delivery_attempts IS 'Number of delivery attempts already made for this cycle.';

COMMENT ON COLUMN SUBSCRIPTION.subscription_deliveries.max_delivery_attempts IS 'Maximum attempts before marking the delivery as permanently failed.';

CREATE INDEX idx_subscription_deliveries_subscription_id ON SUBSCRIPTION.subscription_deliveries (subscription_id);

CREATE INDEX idx_subscription_deliveries_scheduled_date ON SUBSCRIPTION.subscription_deliveries (scheduled_date);

CREATE INDEX idx_subscription_deliveries_status ON SUBSCRIPTION.subscription_deliveries (status);

-- +goose Down
DROP TABLE IF EXISTS SUBSCRIPTION.subscription_deliveries;

DROP TABLE IF EXISTS SUBSCRIPTION.subscription_configs;

DROP TABLE IF EXISTS SUBSCRIPTION.subscriptions;

DROP SCHEMA IF EXISTS SUBSCRIPTION;